[image]
name = "reflect"
width = 1280
height = 1280

[camera]
origin = [0.0, 0.0, 20.0]
view = [0.0, 0.0, -1.0]
up = [0.0, 1.0, 0.0]

[[scene.lights]]
origin = [0.0, 0.0, 5.0]

[[scene.spheres]]
center = [0.0, 3.0, 0.0]
radius = 2.0
  [scene.spheres.properties]
  color = [255, 100, 100]
  reflection = 0.5
[[scene.lights]]
origin = [0.0, -3.0, 5.0]

[[scene.spheres]]
center = [-3.0, -2.0, 0.0]
radius = 2.0
  [scene.spheres.properties]
  color = [100, 255, 100]
  reflection = 0.5
[[scene.lights]]
origin = [3.0, 2.0, 5.0]

[[scene.spheres]]
center = [3.0, -2.0, 0.0]
radius = 2.0
  [scene.spheres.properties]
  color = [100, 100, 255]
  reflection = 0.5
[[scene.lights]]
origin = [-3.0, 2.0, 5.0]

[[scene.spheres]]
center = [0.0, 0.0, -100001.0]
radius = 100000.0
  [scene.spheres.properties]
  color = [200, 200, 200]
  diffusion = 0.2
